const AuthTypes = {
    
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    POST_REQUEST: "POST_REQUEST:",
    POST_SUCCESS: "POST_SUCCESS:"
};

export { AuthTypes };
