const DashboardTypes = {
    USER_DATA_REQUEST: "USER_DATA_REQUEST",
    USER_DATA_REQUEST_SUCCESS: "USER_DATA_REQUEST_SUCCESS",
    PERSON_REQUST:'PERSON_REQUST',
    PERSON_REQUST_SUCCESS:"PERSON_REQUST_SUCCESS",
    DELETE_USER:'DELETE_USER',
    DELETE_USER_SUCCESS:"DELETE_USER_SUCCESS"
};

export { DashboardTypes };

